### ISSUE TITLE
BUN number issue in REP Information tab

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#112]
REP Section -> Information Tab -> Bargaining Unit Number textbox:

Double Right and Double Left clicks bring up the search (is this desired functionality??).  IF there is a BUN already in the text box, and you double click to bring up the search box, then close out of the search box without actually clicking on the BUN that comes up in the search box: the BUN remains unchanged in the text field (as it should), but the description directly below the BUN disappears until you go back into the search box and actually select the BUN again.

I got this error when canceling out from the BUN search without selecting a BUN (as stated above):
	Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at parker.serb.REP.REPCaseInformationPanel.setBUNumberCheckBoxes(REPCaseInformationPanel.java:400)
        at parker.serb.REP.REPCaseInformationPanel.bargainingUnitNumberTextBoxMouseClicked(REPCaseInformationPanel.java:1208)

        at parker.serb.REP.REPCaseInformationPanel.access$300(REPCaseInformationPanel.java:39)
        at parker.serb.REP.REPCaseInformationPanel$4.mouseClicked(REPCaseInformationPanel.java:558)
        at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

**Comment by parkjohnston** [comment]
works double clicking right sid only

**Comment by anthonyperk** [comment]
Not choosing a Bargaining Unit from the "BU Number Search" box and clicking on the "Close" button results in a similar error as above:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at parker.serb.REP.REPCaseInformationPanel.setBUNumberCheckBoxes(REPCaseInformationPanel.java:402)
        at parker.serb.REP.REPCaseInformationPanel.bargainingUnitNumberTextBoxMouseClicked(REPCaseInformationPanel.java:1208)
        at parker.serb.REP.REPCaseInformationPanel.access$300(REPCaseInformationPanel.java:41)
        at parker.serb.REP.REPCaseInformationPanel$4.mouseClicked(REPCaseInformationPanel.java:559)
        at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)

**Comment by anthonyperk** [comment]
Double Right clicking on an empty BU Number text field gives the following CMD Line error (example: 2017-REP-01-0003 has no Bargaining Unit Number chosen.  If I double right click on the empty text field in REP -> Information Tab, I get the error):

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 1
        at parker.serb.sql.BargainingUnit.getCertStatus(BargainingUnit.java:55)
        at parker.serb.bunumber.buNumberSearch.loadInformation(buNumberSearch.java:44)
        at parker.serb.bunumber.buNumberSearch.<init>(buNumberSearch.java:35)
        at parker.serb.REP.REPCaseInformationPanel.bargainingUnitNumberTextBoxMouseClicked(REPCaseInformationPanel.java:1207)
        at parker.serb.REP.REPCaseInformationPanel.access$300(REPCaseInformationPanel.java:39)
        at parker.serb.REP.REPCaseInformationPanel$4.mouseClicked(REPCaseInformationPanel.java:557)
        at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
