### ISSUE TITLE
Error when logging in with a user who has no section access

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#117]
If a user who has not been given access into any sections logs into the system, nothing loads and the following error is printed in the command line window:

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at javax.swing.JTabbedPane.getTitleAt(Unknown Source)
        at parker.serb.RootPanel.setDefaultTab(RootPanel.java:155)
        at parker.serb.RootPanel.<init>(RootPanel.java:89)
        at parker.serb.login.LogInDialog.completeValidLogIn(LogInDialog.java:124)
        at parker.serb.login.LogInDialog.logInButtonActionPerformed(LogInDialog.java:244)
        at parker.serb.login.LogInDialog.access$200(LogInDialog.java:27)
        at parker.serb.login.LogInDialog$5.actionPerformed(LogInDialog.java:173)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicRootPaneUI$Actions.actionPerformed(Unknown Source)
        at javax.swing.SwingUtilities.notifyAction(Unknown Source)
        at javax.swing.JComponent.processKeyBinding(Unknown Source)
        at javax.swing.KeyboardManager.fireBinding(Unknown Source)
        at javax.swing.KeyboardManager.fireKeyboardAction(Unknown Source)
        at javax.swing.JComponent.processKeyBindingsForAllComponents(Unknown Source)
        at javax.swing.JComponent.processKeyBindings(Unknown Source)
        at javax.swing.JComponent.processKeyEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)

**Comment by parkjohnston** [comment]
why would the user be active if they don't have a single section?

this makes no sense

**Comment by anthonyperk** [comment]
andrew brought it to my attention.  I tested to see what would happen.  Ideally it shouldn't ever happen.

I can see this happening where Justin adds a new user, forgets to give them any access to any section, and then creates a ticket about not letting the user in.  He's done far worse.

**Comment by parkjohnston** [comment]
when the user is created they should be forced to assign a role...maybe
that is a validation that needs to happen

**Comment by anthonyperk** [comment]
that could definitely be an option

**Comment by parkjohnston** [comment]
what is the result so this can be fixed and closed?

**Comment by anthonyperk** [comment]
If the user does not have any roles associated with them, would you be able to create a popup that says that?  It would popup after the user logs in

**Comment by parkjohnston** [comment]
"There are no sections assigned for this user

Please contact the system administrator"

**Comment by anthonyperk** [comment]
Functionality Confirmed
