### ISSUE TITLE
Null pointer generating CMDS letters

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#192]
I get the following error when generating CMDS Documents: 
(ex: Reports and Recommendations: Lack of Justisdiction over Parties -> Municipal Employees
and
Board Order and Letters: Board Order -> BO Adopts)
Exception in thread "Thread-4" java.lang.NullPointerException
        at parker.serb.bookmarkProcessing.processCMDSbookmarks.processDoACMDSWordLetter(processCMDSbookmarks.java:252)
        at parker.serb.bookmarkProcessing.generateDocument.generateCMDSdocument(generateDocument.java:126)
        at parker.serb.letterGeneration.LetterGenerationPanel.generateLetter(LetterGenerationPanel.java:497)
        at parker.serb.letterGeneration.LetterGenerationPanel.lambda$processThread$55(LetterGenerationPanel.java:954)
        at java.lang.Thread.run(Unknown Source)

this is also making word appear in the task manager but NOT opening or generating a document

**Comment by altrdgenetics** [comment]
pushed it up, needs to be checked. I do not have the latest set of templates here

**Comment by altrdgenetics** [comment]
the entire model was nulled out if no questions. that was the problem
