### ISSUE TITLE
(PT059) -- CMDS Document will not generate

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#237]
CMDS Tab > Spinning Wheel generating template (Reclassification -> Appellee/Appellant Timeliness QST)

![image](https://cloud.githubusercontent.com/assets/24595073/23614845/63f1c84a-0252-11e7-904f-e3ad247b70cd.png)

**Comment by anthonyperk** [comment]
Error saving the file due to the filename containing a '\'

**Comment by anthonyperk** [comment]
Error:

Exception in thread "Thread-4" com.jacob.com.ComFailException: Invoke of: FileSaveAs
Source: Microsoft Word
Description: This is not a valid file name.
Try one or more of the following:
* Check the path to make sure it was typed correctly.
* Select a file from the list of files and folders.

        at com.jacob.com.Dispatch.invokev(Native Method)
        at com.jacob.com.Dispatch.invokev(Dispatch.java:625)
        at com.jacob.com.Dispatch.callN(Dispatch.java:453)
        at com.jacob.com.Dispatch.call(Dispatch.java:541)
        at parker.serb.bookmarkProcessing.generateDocument.generateCMDSdocument(generateDocument.java:135)
        at parker.serb.letterGeneration.LetterGenerationPanel.generateLetter(LetterGenerationPanel.java:499)
        at parker.serb.letterGeneration.LetterGenerationPanel.lambda$processThread$55(LetterGenerationPanel.java:959)
        at java.lang.Thread.run(Unknown Source)

**Comment by altrdgenetics** [comment]
issue was caused by trying to have a slash in the filename. added a replace all for the text in the save name to remove all invalid windows namespace characters.

**Comment by altrdgenetics** [comment]
with these slash errors, it had been overwriting the templates.
