### ISSUE TITLE
(R3-025) - (Email Server) - Jericho 40 Error while importing email

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#593]
On the SERB Email import program. I received the following error message. I have forwarded the email to the Test email account for review. After reviewing the docket screen it looks like the one email chain was docketed as three entries… one for each response in the email chain.

I just wanted to make you aware of this, in case there was some kind of error catch that could be added to prevent the program from crashing. I was able to restart the application and it processed the remaining items correctly.

Wed, 07/26/2017 09:14:42 PM - Starting Email Thread
Fetching Email for: testdocket@serb.state.oh.us
Fetching Email for: MED@SERB.state.oh.us
Fetching Email for: ULP@SERB.state.oh.us
Fetching Email for: REP@SERB.state.oh.us
2017-07-26 21:14:50 ERROR jericho:40 - Child Element <p>- ((r4,c46,p308)-(r10,c1,p705)) extends beyond end of parent Element <font >-</font> ((r4,c1,p263)-(r5,c8,p451))
log4j:ERROR Failed to flush writer,
java.io.IOException: An unexpected network error occurred
at java.io.FileOutputStream.writeBytes(Native Method)
at java.io.FileOutputStream.write(Unknown Source)
at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
at sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
at sun.nio.cs.StreamEncoder.flush(Unknown Source)
at java.io.OutputStreamWriter.flush(Unknown Source)
at org.apache.log4j.helpers.QuietWriter.flush(QuietWriter.java:59)
at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:324)
at org.apache.log4j.RollingFileAppender.subAppend(RollingFileAppender.java:276)
at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
at org.apache.log4j.Category.callAppenders(Category.java:206)
at org.apache.log4j.Category.forcedLog(Category.java:391)
at org.apache.log4j.Category.error(Category.java:305)
at net.htmlparser.jericho.LoggerProviderLog4J$Log4JLogger.error(LoggerProviderLog4J.java:40)
at net.htmlparser.jericho.Element.getChildElements(Element.java:329)
at net.htmlparser.jericho.Element.getChildElements(Element.java:335)
at net.htmlparser.jericho.Element.getChildElements(Element.java:335)
at net.htmlparser.jericho.Element.getChildElements(Element.java:299)
at net.htmlparser.jericho.Segment.getChildElements(Segment.java:452)
at net.htmlparser.jericho.Renderer$Processor.appendTo(Renderer.java:874)
at net.htmlparser.jericho.Renderer.appendTo(Renderer.java:144)
at net.htmlparser.jericho.CharStreamSourceUtil.toString(CharStreamSourceUtil.java:63)
at net.htmlparser.jericho.Renderer.toString(Renderer.java:154)
at com.email.ReceiveEmail.saveEnvelope(ReceiveEmail.java:223)
at com.email.ReceiveEmail.fetchEmail(ReceiveEmail.java:114)
at com.MainClass.incomingEmails(MainClass.java:230)
at com.MainClass.emailThreads(MainClass.java:189)
at com.MainClass.access$000(MainClass.java:42)
at com.MainClass$1.run(MainClass.java:76)
2017-07-26 21:14:50 ERROR jericho:40 - Child Element <font >-</font> ((r8,c1,p652)-(r14,c8,p1041)) extends beyond end of parent Element <p>- ((r4,c46,p308)-(r10,c1,p705))
Exception in thread "Thread-2" java.lang.NoClassDefFoundError: com/sun/mail/imap/IMAPNestedMessage
at com.sun.mail.imap.IMAPBodyPart.getDataHandler(IMAPBodyPart.java:296)
at javax.mail.internet.MimeBodyPart.getContent(MimeBodyPart.java:657)
at com.email.ReceiveEmail.saveAttachments(ReceiveEmail.java:309)
at com.email.ReceiveEmail.saveAttachments(ReceiveEmail.java:306)
at com.email.ReceiveEmail.fetchEmail(ReceiveEmail.java:118)
at com.MainClass.incomingEmails(MainClass.java:230)
at com.MainClass.emailThreads(MainClass.java:189)
at com.MainClass.access$000(MainClass.java:42)
at com.MainClass$1.run(MainClass.java:76)
Caused by: java.lang.ClassNotFoundException: com.sun.mail.imap.IMAPNestedMessage
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 9 more

![image](https://user-images.githubusercontent.com/24595073/28671411-94c3f344-72aa-11e7-830a-fa45d7bbef98.png)

![image](https://user-images.githubusercontent.com/24595073/28671415-972f9c96-72aa-11e7-8a29-4ef62aa3a8ba.png)

**Comment by parkjohnston** [comment]
java.io.IOException: An unexpected network error occurred

is stated right at the start of the error...I would put this on OIT and not an XLN Bug

**Comment by altrdgenetics** [comment]
emailed Justin, said it is out of our control. pointed the finger to network and REP using that rich content on their emails
