### ISSUE TITLE
(R3-100) - (CMDS) - Issue when docketing into cases that have group numbers

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#669]
When docketing to a case with a Group Number assigned, it asks if you want to docket to all cases in the group number. Regardless of whether I choose yes or no, it still dockets to all of the cases.

Example Cases
18-LAY-02-0029
18-ABL-02-0030
18-LAY-02-0031

**Comment by anthonyperk** [comment]
AMENDMENT FROM JUSTIN

>Examples: 

>Group of 4 cases.

> Enter 1 case number, it asks "Do you want to docket into all group cases?" Y/N
> If Yes, put in all cases, If No, put in only the identified case.

> Group of 4 cases.
> User enters case 1 and 2 separated by a comma
> If Yes, put in all cases (do not create duplicates), If No, put in only the 2 entered cases.

**Comment by altrdgenetics** [comment]
Need to verify with Justin about scenerios.

Example, if the user attempts to docket to 2 or more cases that are within the same group the system is currently docketing n# of duplicates in each case equal to the cases that the user manually put it on the docket screen eg. case group of 10, user manually enters 3 of the cases from that group. the docket will put 3 of the same entries into each case

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> Anthony, 
> 
> In the examples that I provided I am trying to communicate the following:
> 
> If in a group and “Yes” is selected, put a copy of the document and activity entry into each case… if more than one case was entered in the docketing screen (separated by a semicolon), check for duplicate case numbers from the group to ensure the document does not get duplicated during the docket when performing the loop function.
> 
> If in a group and “No” is selected, put a copy of the document and activity entry into only the case that was entered in the docketing screen… if more than one case was entered put it into the cases that were typed in the docketing screen (separated by a semicolon)

**Comment by altrdgenetics** [comment]
How much time/effort are they wanting to put into this. The way that the code is currently laid out the question for the multicase docket is buried way deep into the process for the attachments. Major changes will need to occur.

from the file email panel it goes to the File service with the comma separated list of cases, from there it loops the individual case numbers and then attempts to docket each one (FileService.java ln: 635). This is the point that we lose the total group number and beyond this we lose any chance to remove duplicate case numbers. At the end of that method it goes to CMDSCaseDocketEntryTypes.updateCaseHistory; at that point it breaks down for each of the category types that CMDS section has, so depending on which type it has different actions that occur. Not until we are in there does it check for updating the cases by group number. 

And right now the only way it asks if you want to update the group case is if it is also updating the inventory status line. if you go through and say no there is an else clause that will just auto add the activity entry to each case in the group. So even if you are updating the the initial case number it will docket to all cases no matter what.

The requested change makes sense but It does not work like they think and will be a mess to change as each type has its own code block and we have almost a full alphabet to change over. It will be time consuming.

**Comment by altrdgenetics** [comment]
Test cases used, first 3 are group#: 20180084, 4th case is group#: 20180096, and last one has no case number

`2018-OSH-04-0084, 2018-OSH-04-0085, 2018-OSH-04-0086, 2018-REC-05-0096, 2018-IDS-07-0129`

**Comment by altrdgenetics** [comment]
Since we are consolidating the update every case, should we also be consolidating the "update status inventory line" as well?

**Comment by anthonyperk** [comment]
FROM JUSTIN

> Regarding ticket R3-100, I do not believe the status line gets updated when docketing a new document into it. 
> 
> In ticket R3-091, the inventory status line question is addressed for outgoing documents. The inventory status line would be updated in the other cases that receive the document if the inventory status line is updated in the master case. 
> 
> Yes the inventory status line should be consolidated while cases are grouped. If a case is removed from the group at a later time the consolidation would stop for that case.

**Comment by altrdgenetics** [comment]
The question is asked:

https://github.com/CurrentlyNotSet/SERB/blob/develop/src/main/java/parker/serb/CMDS/CMDSCaseDocketEntryTypes.java#L131

shortly after the "update group" is asked if in a group:

https://github.com/CurrentlyNotSet/SERB/blob/develop/src/main/java/parker/serb/CMDS/CMDSCaseDocketEntryTypes.java#L142

Since it is being moved forward I was asking if the other since Justin has referenced 2 tickets, please ensure that he wants it done on incoming documents through docket process.

**Comment by anthonyperk** [comment]
Update to the Ticket:

Justin would like added functionality.  When a user inputs a case or cases into the docketing screen, and that/those cases are in a group (either together or in separate groups), SERB would like to have a dialog window to pop-up saying something along the lines of:
"The Entered case(s) are associated with a group or groups, would you like to docket this to all of the cases in the group(s)" with a Yes or No option.

----If No, docket only to the cases entered in the docket window

----If yes, another screen appears with a list of all of the case numbers in the group, the group number/id, and a check mark box (sorted by Group Number/ID, then by Case Number).  When populated, **the list will have all of the checkmarks checked as a default** and the USER will need to select if any of the cases should be excluded.  Once the User has finished with any selections, a 'Docket' button at the bottom will then proceed with the docketing process to all checkmarked cases.  A cancel button going back to the original docketing window should be added as well.

Example:

18-LAY-02-0029 (This is in a group, ID 1)
18-ABL-02-0030 (This is in a group, ID 1)
18-LAY-02-0034 (This is in a group, ID 2)
18-LAY-02-0037 (This is not in a group)

The new window should look like this:
![image](https://user-images.githubusercontent.com/24595073/47225033-0c97f400-d38b-11e8-9dc2-e2c9828c67bc.png)

**Comment by altrdgenetics** [comment]
I have updated the changes to the newly requested SERB information. I have not created a merge request yet. Please take and pull down this version and test locally before to make sure this is indeed what SERB is looking for. Maybe even get a demo with Justin to ensure it is correct. I did take come liberties in when it would ask all of the necessary questions outside of the information from Justin. For example the update status inventory line will ask for each email attachment line item but it is a all/none when it comes to cases. This assumption was made to limit required clicks but give the flexibility of each docketed item. I have also added in case number references to some of the popups, I do not know if all were gotten. The original setup was designed around a single case or group Number. The new format allows for flexibility for cases which may not share the same group. These changes were made with this in mind.

As far as testing goes all of the following have been touched/modified:

- CMDS Email Process
- CMDS Scan Process
- CMDS Media Process
- CMDS Add Activity Process


Due to this please pull down and verify that everything is working as intended and there is no issues with crashing. I have tested all of these roughly to ensure that they work and the correct number of dockets have occured. Please verify that the data that is put in is correct as well since the process moves across several different files before the process is finished.

**Comment by anthonyperk** [comment]
TESTING RESULTS

![image](https://user-images.githubusercontent.com/24595073/49313304-cb7c1f00-f4b4-11e8-83c7-5ae1aa069f1b.png)

Got the following error when hitting the file button

Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: parker.serb.CMDS.CMDSUpdateInventoryStatusLineDialog.<init>(Ljava/awt/Dialog;ZLjava/lang/String;)V
	at parker.serb.docket.scanCMDSFileDialog.fileButtonActionPerformed(scanCMDSFileDialog.java:536)
	at parker.serb.docket.scanCMDSFileDialog.access$500(scanCMDSFileDialog.java:35)
	at parker.serb.docket.scanCMDSFileDialog$7.actionPerformed(scanCMDSFileDialog.java:352)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1673)
	at java.awt.Component.setVisible(Component.java:1625)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at parker.serb.docket.scanCMDSFileDialog.<init>(scanCMDSFileDialog.java:57)
	at parker.serb.docket.DocketRootPanel.displayFileDialog(DocketRootPanel.java:309)
	at parker.serb.docket.DocketRootPanel$5.mouseClicked(DocketRootPanel.java:261)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6538)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



Tried this for all 4 Docketing methods, same result.
