### ISSUE TITLE
2020-011 - (REP/MED) - Adding new Employers to the Employers table (Previously: MED Section Employer/BUN Lookup issue)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#740]
Recently a new employer and BUN number was added to the system in the REP section (3354-01). The parties then filed a notice to negotiate in the MED section.

When searching by BUN number the employer does populate and it updates the employer ID field and BUN Number field. (This works)
![image](https://user-images.githubusercontent.com/24595073/76430969-566de980-6387-11ea-8911-dd7a9c3e40d0.png)

When Searching by Employer ID, Employer 3354 does not populate. **This needs corrected.**
![image](https://user-images.githubusercontent.com/24595073/76431001-5ec62480-6387-11ea-99fe-310cd0f6e516.png)

File > BU Information Screen. (This should be where this info is being pulled from)
This new information was entered and updated by the REP section a while back.
![image](https://user-images.githubusercontent.com/24595073/76431017-6685c900-6387-11ea-8f73-28be8149400b.png)

**Comment by anthonyperk** [comment]
This is all due to not being able to add employers.  This ticket is now being re-used for the new Employer functionality.

What is desired:
File -> BU Information panel -> Create new Button -> Double Clicking on the Employer number field brings up a search box.  This should also have a 'create new' button similar to the BU Number Search panel.  This button will bring up another panel with the following information (all information is required):

- Employer Number (which is given to the worker by Clearing House)
- Employer Name
- Employer County Drop down (same as the current down down in the Bargaining Unit Information panel)
- Employer Type (new drop down with employer types, will most likely be static)
- Jurisdiction (new drop down with Jurisdiction codes)

So long as the Employer Number doesn't already exist in the table, the Employer information should be saved.

Note: When Saving the information in the Bargaining Unit Information panel, employer number must not be null/blank.

**Comment by altrdgenetics** [comment]
heads up there is quite a few fields missing from this original employers panel... will have to rewrite it to get all of the data back from the database.


![Screenshot (86)](https://user-images.githubusercontent.com/8847344/80314069-0626db80-87bd-11ea-86bf-780dc002fccd.png)

**Comment by altrdgenetics** [comment]
With the New Fields I am not convinced about the layout anymore. And since we don't have something to look at from XLNCMS I am not sure their preferred layout. Can you check with Justin, there are a few fields like Jurisdiction and such that could potentially be grouped differently.


![Screenshot (87)](https://user-images.githubusercontent.com/8847344/80314471-b0076780-87bf-11ea-9bc2-e450f0fb6bdc.png)

**Comment by anthonyperk** [comment]
I was asked to add a few employers into the employer table, and all Justin wanted added was the following fields:  BUN, Public Employer, County, Employer Type, Jurisdiction.

As for the Type Code, I would think we could make a new table with the codes?  Or would you prefer to make it freehand?

**Comment by anthonyperk** [comment]
Email from JUSTIN

The only fields/columns that are needed are the following:

ID
Active                                   Yes
Employer ID                       0851
BUN                                       0851-01
Public Employer               KENSTON LOCAL SCHOOLS
County                                 GEAU
Jurisdiction                        BE  
Employer Type                  LO

**Comment by altrdgenetics** [comment]
What is public employer? I do not see that in the database table.

Also wouldnt BUN be a subset of data, within the bargining unit table. It is not something that is available at the top level for creating an Employer.

**Comment by anthonyperk** [comment]
Public Employer is just the Employer Name

One would think that the BUN would only be populated once an employer was associated with it.  I will ask to see if its necessary within the employers table

**Comment by anthonyperk** [comment]
Public Employer is just the Employer Name

Justin says leave the BUN number out of the new employer panels.  The BUN will link up through the 'New BUN' panel like it is now.

**Comment by anthonyperk** [comment]
TESTING RESULTS
--------------------
Adding the employer worked from:
1) File -> BU Information -> BU Number Search Panel -> Create New Button -> Double Clicking on Employer Name field -> New button on Employer Search panel

2) Adding an employer within a section's Information/Status tab.

ISSUES
--------------
1) After adding a new employer, the Employer search didnt list them until I restarted the application.  I searched on name, case number, and Employer ID.  I also hit the refresh button a few times.  None worked until the application was restarted.  Then they all worked.

2) Should an 'add new employer' button be added to the Employer Search tab as well?

**Comment by anthonyperk** [comment]
Justin also requests the following:

Please make sure the code verifies that the employer ID does not already exist and that it adds the leading zeros like the others already shown in the system. 

Will we be able to edit existing entries (like if they change their name? or will that need to be done on the backend? The thought just occurred to me.

**Comment by altrdgenetics** [comment]
Made some minor tweaks for loading the information after creation and then added leading zeros and a prevention window for doubling up employerID numbers. 

There is nothing in the system for updating existing entries, this will need to be done on the back end for the time being.

**Comment by anthonyperk** [comment]
Looks good to me!

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

I also tested ticket 2020-011 (Adding new Employers to the Employers Lookup Table (for creation of Bargaining Unit Numbers in REP). The test successfully added the employer to the table so that REP can create new BUN numbers. 

I am seeking a few tweaks to this to improve workflow.  

1)	Change the order by moving Employer Type Code to the bottom. It should come after Jurisdiction.  The order should be:
a.	Employer ID Number
b.	Employer Name
c.	County
d.	Jurisdiction
e.	Employer Type Code
![image](https://user-images.githubusercontent.com/24595073/85052223-8f77e000-b166-11ea-9ec3-99987b89bd07.png)

2)	Change Employer Type Code to a dropdown box that contains the attached list of two digit codes. 
3)	There appears to be no way to edit an existing entry in the Employer Lookup Table once it is created. Can you add a right click edit feature to the Employer Search screen? This would allow us to fix if misspelled or if the employer name changes. 
![image](https://user-images.githubusercontent.com/24595073/85052281-a28ab000-b166-11ea-923f-ce8c832aa1a3.png)
a) Note: I did find that I could edit the employer name after it was loaded into the BUN Table (As shown in the example below by pressing the update button and making the manual change.) 
![image](https://user-images.githubusercontent.com/24595073/85052330-b504e980-b166-11ea-8f3b-a66bcbff7b57.png)

4)	The Employer Name appears two different ways in the BU Number Search field. Either Upper Case or Proper Case. The original info was uppercase and the newly added info is Proper case.  For consistency we should consider choosing one method. I am leaning towards Upper Case to avoid capitalization issues for the Employer and Union Name for this table. I am not sure if the employer Table is used anywhere else in the database as a lookup table. (Discussion Item)

![image](https://user-images.githubusercontent.com/24595073/85052361-c0581500-b166-11ea-9011-5ff0c7f0efaa.png)

**Comment by anthonyperk** [comment]
1) I am sure the reorder of the fields is pretty easy

2) I attached the Type Codes.  I asked if this was static perhaps we could hard code them in?  If not, its gonna be a database table and thats more work.  Attached is the spreadsheet
[Employer Type Codes.xlsx](https://github.com/CurrentlyNotSet/SERB/files/4800165/Employer.Type.Codes.xlsx)

3) I think this is a non issue, as he found how to edit the name all on his own.

4) I wouldnt be surprised if they ask for all of the existing names to be upper case, and the application to force the new names to be uppercase.  The BarginingUnit table is where the information is being pulled from.  The Employers table is largely Proper Case.  Not sure what to do here. 

***SOMETHING I FOUND***
In the 'Bargining Unit Information' panel (File -> BU Information -> Create New button on the BU Number Search ->  'Bargining Unit Information' panel), Bargaining Unit is misspelled as Bargining Unit.  Maybe we should change that before they notice.

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

Yes it is misspelled. Should be “Bargaining Unit Information”

**Comment by anthonyperk** [comment]
TESTING RESULTS

1) Good

2) Good

3) When editing an employer from the Employer Search Panel (Employer Search panel -> select employer then right click on it) when I hit save, an error pops up saying the employer ID is already in use.
![image](https://user-images.githubusercontent.com/24595073/86028101-848f3c00-b9ff-11ea-9428-bbfa90d59bfd.png)

4) For a later time

Misspelling) Correct

**Comment by anthonyperk** [comment]
Now works

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

I found the following issues. Can these be fixed at no charge?

1)	When entering a new employer ID, I fill them in top to bottom and the save stays greyed out. I then click on Employer ID Number then the save button shows. 
2)	I press save and I get the Null Pointer Exception (Example 2 below).
3)	The system does allow me to edit and save an existing employer name without error. (Example 3 Below).
Example 1
 
![image](https://user-images.githubusercontent.com/24595073/87473869-2c0b9180-c5f0-11ea-80be-a4622ccc4845.png)


Example 2
Starting SERB Case Management Application - v3.12.0




Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at parker.serb.employer.employerDetailAdd.saveInformation(employerDetailAdd.java:122)
        at parker.serb.employer.employerDetailAdd.jButton2ActionPerformed(employerDetailAdd.java:322)
        at parker.serb.employer.employerDetailAdd.access$500(employerDetailAdd.java:19)
        at parker.serb.employer.employerDetailAdd$6.actionPerformed(employerDetailAdd.java:234)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at java.awt.Component.show(Unknown Source)
        at java.awt.Component.setVisible(Unknown Source)
        at java.awt.Window.setVisible(Unknown Source)
        at java.awt.Dialog.setVisible(Unknown Source)
        at parker.serb.employer.employerDetailAdd.<init>(employerDetailAdd.java:41)
        at parker.serb.employer.employerSearch.NewButtonActionPerformed(employerSearch.java:306)
        at parker.serb.employer.employerSearch.access$400(employerSearch.java:27)
        at parker.serb.employer.employerSearch$6.actionPerformed(employerSearch.java:259)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at java.awt.Component.show(Unknown Source)
        at java.awt.Component.setVisible(Unknown Source)
        at java.awt.Window.setVisible(Unknown Source)
        at java.awt.Dialog.setVisible(Unknown Source)
        at parker.serb.employer.employerSearch.<init>(employerSearch.java:69)
        at parker.serb.bunumber.BUInformationNewDialog.employerNumberTextBoxMouseClicked(BUInformationNewDialog.java:563)
        at parker.serb.bunumber.BUInformationNewDialog.access$000(BUInformationNewDialog.java:29)
        at parker.serb.bunumber.BUInformationNewDialog$1.mouseClicked(BUInformationNewDialog.java:278)
        at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
       at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at java.awt.Component.show(Unknown Source)
        at java.awt.Component.setVisible(Unknown Source)
        at java.awt.Window.setVisible(Unknown Source)
        at java.awt.Dialog.setVisible(Unknown Source)
        at parker.serb.bunumber.BUInformationNewDialog.<init>(BUInformationNewDialog.java:43)
        at parker.serb.bunumber.BUNumberFileAddUpdateDeleteDialog.CreateNewButtonActionPerformed(BUNumberFileAddUpdateDeleteDialog.java:252)
        at parker.serb.bunumber.BUNumberFileAddUpdateDeleteDialog.access$300(BUNumberFileAddUpdateDeleteDialog.java:23)
        at parker.serb.bunumber.BUNumberFileAddUpdateDeleteDialog$5.actionPerformed(BUNumberFileAddUpdateDeleteDialog.java:205)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at java.awt.Component.show(Unknown Source)
        at java.awt.Component.setVisible(Unknown Source)
        at java.awt.Window.setVisible(Unknown Source)
        at java.awt.Dialog.setVisible(Unknown Source)
        at parker.serb.bunumber.BUNumberFileAddUpdateDeleteDialog.<init>(BUNumberFileAddUpdateDeleteDialog.java:40)
        at parker.serb.RootPanel.jMenuItem8ActionPerformed(RootPanel.java:2282)
        at parker.serb.RootPanel.access$1800(RootPanel.java:88)
        at parker.serb.RootPanel$19.actionPerformed(RootPanel.java:1784)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

Example 3
 
![image](https://user-images.githubusercontent.com/24595073/87473913-3c237100-c5f0-11ea-91c9-10c4bc3197ce.png)

**Comment by anthonyperk** [comment]
1) Confirmed that this is a legit issue.  Everything filled out, but you have to click into the "Employer ID Number" field in order for the save button to become active.

2) Confirmed that this also legit.  I did not get this error when testing, but it had to have been there.

3) At least something worked.  Yay?

**Comment by anthonyperk** [comment]
Justin confirms this works correctly
