### ISSUE TITLE
Pull Date not formatted correctly

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#91]
CMDS -> Activity Tab -> Add Entry Button -> Add History Entry box -> Green Card Information box:

The Pull Date is not formatted correctly.  System will not save the record because of it.

Currently formatted: 18.01.2017

On Ticket T009

**Comment by parkjohnston** [comment]
3dddfea69c6abb633470c14f8a5302e8410dc093

**Comment by anthonyperk** [comment]
when the OK button on the "Green Card information" screen is clicked, nothing happens.  When I exit out of that panel, then close out of the 'Add Entry' panel, I got the following error:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at parker.serb.CMDS.CMDSCaseHistoryEntryTypes.greenCardWhichDate(CMDSCaseHistoryEntryTypes.java:1657)
        at parker.serb.CMDS.CMDSCaseHistoryEntryTypes.addQEntryType(CMDSCaseHistoryEntryTypes.java:1157)
        at parker.serb.CMDS.CMDSCaseHistoryEntryTypes.updateCaseHistory(CMDSCaseHistoryEntryTypes.java:106)
        at parker.serb.CMDS.CMDSAddHistoryEntryDialog.saveButtonActionPerformed(CMDSAddHistoryEntryDialog.java:353)
        at parker.serb.CMDS.CMDSAddHistoryEntryDialog.access$500(CMDSAddHistoryEntryDialog.java:22)
        at parker.serb.CMDS.CMDSAddHistoryEntryDialog$6.actionPerformed(CMDSAddHistoryEntryDialog.java:222)

**Comment by parkjohnston** [comment]
49404cc6377a443f486b35f7917775c4212a978f
